name: Integration Tests with GlassFish

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
    - name: Run Tests on Glassfish
      run: mvn -B -q clean verify -Parq-glassfish-managed
    - uses: actions/upload-artifact@v4
      if: failure()
      with:
        name: glassfish-server-log
        path: data/target/glassfish*/glassfish/domains/domain1/logs/server.log  
